site_name: pygeekbot
site_description: Python SDK for Geekbot API
repo_url: https://github.com/yaugenst/pygeekbot
site_url: https://yaugenst.github.io/pygeekbot
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.tracking

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mike:
      canonical_version: latest
      version_selector: true
      css_dir: css
      javascript_dir: js
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [pygeekbot]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 1
            docstring_style: numpy

nav:
  - Home: index.md
  - API Reference:
    - Client: reference/client.md
    - API: reference/api.md
    - Models: reference/models.md
    - Exceptions: reference/exceptions.md
    - Utils: reference/utils.md

extra:
  version:
    provider: mike
    alias: true
    default: latest

extra_css:
  - css/version-select.css
