name: tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run tests 🧪
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    outputs:
      success: ${{ steps.tests.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: |
          uv sync --group tests

      - id: tests
        name: Run tests and lint
        run: |
          uv run --python-preference only-system ruff check .
          uv run --python-preference only-system pytest tests/ --cov=pygeekbot --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
